### ISSUE TITLE
multi-architecture docker image?

### ISSUE THREAD

**Issue by denisa** [assignUser/chktex-alpine#3]
the arm64 architecture is more commonky used since Apple’s release of their M1-based mac.

Please provide a docker image that also supports that architecture.

**Comment by assignUser** [comment]
I should be able to set that up with buildx, will have a look soon

**Comment by assignUser** [comment]
Sorry for the delay, linux/arm64 has been added to [v0.2.0](https://github.com/assignUser/chktex-alpine/pkgs/container/chktex-alpine/122308127?tag=v0.2.0)!
